baseURL                = 'https://hencte.top/'
languageCode           = 'zh'
title                  = '亦幸小阁'
defaultContentLanguage = 'zh'
theme                  = "kiss"
relativeURLs           = true
enableEmoji            = true
enableGitInfo          = true
summaryLength          = 200

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true

[languages]
  [languages.zh]
    weight = 0
  [languages.en]
    weight = 1

[[menus.main]]
  name    = 'Home'
  pageRef = '/'
  weight  = 10
[[menus.main]]
  name    = 'Posts'
  pageRef = '/log'
  weight  = 20
[[menus.main]]
  name    = 'Tags'
  pageRef = '/tags'
  weight  = 30


[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'